sudo: required
services: 
  - docker

before_install:
  - docker build -t sherif93/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sherif93/react-test npm run test -- --coverage

after_success:
  - docker build -t sherif93/multi-client ./client  
  - docker build -t sherif93/multi-nginx ./nginx  
  - docker build -t sherif93/multi-server ./server  
  - docker build -t sherif93/multi-worker ./worker
  # Log in to the docker CLI
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push sherif93/multi-client
  - docker push sherif93/multi-nginx
  - docker push sherif93/multi-server
  - docker push sherif93/multi-worker